### ISSUE TITLE
error occurs when i put .dll file in plugins

### ISSUE THREAD

**Issue by zzsuki** [JuergenKosel/s7commwireshark#3]
it occurs an error when i open wireshark after putting dll file in `plugins/3.2/epan/`, error info like this:
![image](https://user-images.githubusercontent.com/57662555/96567498-6b393500-12f9-11eb-82d1-8f680f6ebc76.png)

version of wireshark is 3.2.7, and my paltform is win10, i need to do some works with s7comm-plus recentlly, it would be appreciate if this plugins can be used

**Comment by JuergenKosel** [comment]
Hello,

the wireshark from https://github.com/JuergenKosel/wireshark already contais the S7-comm-plus dissector. Therefore you should not add another instance of the  dissector dll.
